### ISSUE TITLE
When caching, reloading causes nil:NilClass error

### ISSUE THREAD

**Issue by lulalala** [janko-m/flickr-objects#13]
Thanks for developing this gem.

I have a simple app which loads images from one photoset.

    Flickr.sets.find("72157664303483194").photos(size:true)

It works well. However, after enabling caching, it will fail after 2nd page load (when fetching from cache)
I am using the `config.cache = ActiveSupport::Cache::MemoryStore.new(expires_in: 1.day)` setting.

https://github.com/janko-m/flickr-objects/blob/master/lib/flickr/api/set.rb#L65 is where the issue occurred. The `response["photoset"].delete("photo")` returns nil, because response does not contain `photo` param.

**Comment by janko-m** [comment]
I'm not able to reproduce this. Could you come up with a self-contained example that reproduces the problem? You could try modifying my attempt:

```rb
require "flickr-objects"
require "active_support/all"

Flickr.configure do |config|
  config.api_key = "..."
  config.shared_secret = "..."
  config.cache = ActiveSupport::Cache::MemoryStore.new(expires_in: 1.day)
end

p Flickr.sets.find("72157664303483194").photos(sizes: true).map(&:id)
p Flickr.sets.find("72157664303483194").photos(sizes: true).map(&:id)
```

**Comment by lulalala** [comment]
For some reason, when I am in the console, doing it the 3rd time would results in error. Could you try again please?

**Comment by janko-m** [comment]
Thanks, I was able to reproduce, I should be able to determine what's the problem now and fix it.
