### ISSUE TITLE
Generate source URLs of photos from their farm and secret

### ISSUE THREAD

**Issue by janko** [janko-m/flickr-objects#5]
So far the source URLs of photos are picked up from the response hash. But Flickr describes how you can generate those source URLs out of photo's farm and secret.

[http://www.flickr.com/services/api/misc.urls.html](http://www.flickr.com/services/api/misc.urls.html)

The only problem is that the sizes "Large 1600", "Large 2048" and "Original" don't follow this rule. This could bring potential confusion to the users of this gem.

So I don't know if this is worth doing anyways.

**Comment by lulalala** [comment]
I am trying to get the largest size, which is `Original`. However for my photos, `@attributes.fetch("originalsecret")` would cause a `key not found: "originalsecret"` exception. This results in nil being returned.

>  "Original" don't follow this rule

Is that related to my issue? If yes, is my only workaround to use `large1024!`?

Cheers!

**Comment by janko-m** [comment]
I think absence of `originalsecret` and `originalformat` can only happen if you didn't call `flickr.photos.getInfo` on the photo (`photo.get_info!` in flickr-objects). You either have to do that, or you can limit the maximum size with `photo.large1024_or_smaller!`, which will return the largest size capped to "Large 1024".

**Comment by lulalala** [comment]
Thanks it works. Does it makes sense to call `get_info!` implicitly prior to the fetching?

**Comment by janko-m** [comment]
I don't it's a good idea to make implicit HTTP requests, it might be very surprising, I prefer that users always make API calls explicitly. It's a bit unfortunate that Flickr has a strange API (read "crappy"), but I can only go with patching it so far :smile:
